### ISSUE TITLE
I have cloned your project here

### ISSUE THREAD

**Issue by IncimathCal** [MMCInstances/OptifineInstances#6]
and updated for 1.16.3
https://github.com/dujinhuachinaeddie/OptiFineInstances

**Comment by BraydenMotion** [comment]
Hey! Thank you for contributing! There are a few issues I've found.

1. You need to submit a pull request in order for me to merge your clone into this repository.
2. You have committed a system file. (.DS_Store) This should be added to the `.gitignore` file.
3. You have committed your `.minecraft` folder. It happens to contain your logs, which could be a privacy concern for you. It also contains some settings files which would inconvenience people who want to use these instances.
4. You have changed the name of the instance folder. While I don't think this will cause any issues, it deviates from the naming convention thus far.

Other than that, everything seems great! I've realized some improvements I could make to prevent issues like this and I'll be adding those very soon.

**Comment by BraydenMotion** [comment]
I decided it would be easier for me to update to 1.16.3 myself so I've done that. Again, thank you for contributing!

**Comment by IncimathCal** [comment]
Thanks for your message
