### ISSUE TITLE
How would we go about adding a custom version and meta file?

### ISSUE THREAD

**Issue by futurelucas4502** [MMCInstances/OptifineInstances#9]
So right now there isn't support for 1.16.3 however id like to use 1.16.3 so how would i go about doing that? i have the 1.16.3 jar file and a 1.16.3 json meta file but im not sure how i would add these to multimc and can't find what im looking for on google

**Comment by BraydenMotion** [comment]
There is a 1.16.3 instance [here](https://github.com/MMCInstances/OptifineInstances/releases/tag/v1.16.3-0.1).

Instructions for creating an instance are in [CONTRIBUTING.md](https://github.com/MMCInstances/OptifineInstances/blob/master/CONTRIBUTING.md)
